### ISSUE TITLE
How to run the project in Visual studio 2015

### ISSUE THREAD

**Issue by farooksk** [RickStrahl/AlbumViewerVNext#2]
I have tried the project through cmd its working but when i am trying to work with visual studio 2015.
the source files of AlbumViewerBusiness, AlbumViewerNetCore, WestWind.Utilities are failed to load.

Please can you tell me procedure to run the project in visual studio 2015 with all prerequisites.

Thanks,
Farook

**Comment by RickStrahl** [comment]
Are you pulling this repo from the `Last.NET1.01Version` tag? 

Otherwise the current solution won't work. You need Visual Studio 2017 for the current builds as it's using the new .csproj file support in .NET core which is only supported in Visual Studio 2017. The above tag is the last version that still supports `project.json` and works in VS 2015.

**Comment by farooksk** [comment]
sorry i didn't get this point (Are you pulling this repo from the Last.NET1.01Version tag?)

Can you please elaborate ?

**Comment by farooksk** [comment]
pulling this repo from 1.1.1 version

**Comment by RickStrahl** [comment]
You need to pull from this release or earlier.

https://github.com/RickStrahl/AlbumViewerVNext/releases/tag/Last.NET1.01Version

**Comment by farooksk** [comment]
please guide me how to add page with report functionality in this project.

if have any document kind of thing please share with me


Thanks,
Farook

**Comment by RickStrahl** [comment]
This is not the right forum to ask how to questions and this question is off topic to boot. Sorry.
